theme: jekyll-theme-slate
title: Análisis de protestas
description: Proyecto para identificar el número de protestas asociadas a cuestionarios de opinión 
en función de la distancia espacial y temporal de las protestas. Investigador principal Rodolfo disi.
url: https://coes.cl/
link: http://rodolfodisi.com/
